// Code generated by mockery v2.20.2. DO NOT EDIT.

package service

import (
	context "context"

	aiven "github.com/aiven/aiven-go-client/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, project, service
func (_m *MockInterface) Get(ctx context.Context, project string, service string) (*aiven.Service, error) {
	ret := _m.Called(ctx, project, service)

	var r0 *aiven.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*aiven.Service, error)); ok {
		return rf(ctx, project, service)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *aiven.Service); ok {
		r0 = rf(ctx, project, service)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiven.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, project, service)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockInterface(t mockConstructorTestingTNewMockInterface) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
