// Code generated by mockery. DO NOT EDIT.

package service

import (
	context "context"

	aiven "github.com/aiven/aiven-go-client/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, project, _a2
func (_m *MockInterface) Get(ctx context.Context, project string, _a2 string) (*aiven.Service, error) {
	ret := _m.Called(ctx, project, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *aiven.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*aiven.Service, error)); ok {
		return rf(ctx, project, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *aiven.Service); ok {
		r0 = rf(ctx, project, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aiven.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, project, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
//   - _a2 string
func (_e *MockInterface_Expecter) Get(ctx interface{}, project interface{}, _a2 interface{}) *MockInterface_Get_Call {
	return &MockInterface_Get_Call{Call: _e.mock.On("Get", ctx, project, _a2)}
}

func (_c *MockInterface_Get_Call) Run(run func(ctx context.Context, project string, _a2 string)) *MockInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockInterface_Get_Call) Return(_a0 *aiven.Service, _a1 error) *MockInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInterface_Get_Call) RunAndReturn(run func(context.Context, string, string) (*aiven.Service, error)) *MockInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
