// Code generated by mockery v2.20.2. DO NOT EDIT.

package service

import (
	context "context"

	aiven "github.com/aiven/aiven-go-client/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockNameResolver is an autogenerated mock type for the NameResolver type
type MockNameResolver struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx, project
func (_m *MockNameResolver) List(ctx context.Context, project string) ([]*aiven.Service, error) {
	ret := _m.Called(ctx, project)

	var r0 []*aiven.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*aiven.Service, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*aiven.Service); ok {
		r0 = rf(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*aiven.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResolveKafkaServiceName provides a mock function with given fields: ctx, project
func (_m *MockNameResolver) ResolveKafkaServiceName(ctx context.Context, project string) (string, error) {
	ret := _m.Called(ctx, project)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, project)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockNameResolver interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockNameResolver creates a new instance of MockNameResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockNameResolver(t mockConstructorTestingTNewMockNameResolver) *MockNameResolver {
	mock := &MockNameResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
