// Code generated by mockery. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockNameResolver is an autogenerated mock type for the NameResolver type
type MockNameResolver struct {
	mock.Mock
}

type MockNameResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNameResolver) EXPECT() *MockNameResolver_Expecter {
	return &MockNameResolver_Expecter{mock: &_m.Mock}
}

// ResolveKafkaServiceName provides a mock function with given fields: ctx, project
func (_m *MockNameResolver) ResolveKafkaServiceName(ctx context.Context, project string) (string, error) {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for ResolveKafkaServiceName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, project)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNameResolver_ResolveKafkaServiceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveKafkaServiceName'
type MockNameResolver_ResolveKafkaServiceName_Call struct {
	*mock.Call
}

// ResolveKafkaServiceName is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
func (_e *MockNameResolver_Expecter) ResolveKafkaServiceName(ctx interface{}, project interface{}) *MockNameResolver_ResolveKafkaServiceName_Call {
	return &MockNameResolver_ResolveKafkaServiceName_Call{Call: _e.mock.On("ResolveKafkaServiceName", ctx, project)}
}

func (_c *MockNameResolver_ResolveKafkaServiceName_Call) Run(run func(ctx context.Context, project string)) *MockNameResolver_ResolveKafkaServiceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNameResolver_ResolveKafkaServiceName_Call) Return(_a0 string, _a1 error) *MockNameResolver_ResolveKafkaServiceName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNameResolver_ResolveKafkaServiceName_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockNameResolver_ResolveKafkaServiceName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNameResolver creates a new instance of MockNameResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNameResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNameResolver {
	mock := &MockNameResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
