//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package nais_io_v1

import (
	appsv1 "k8s.io/api/apps/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicy) DeepCopyInto(out *AccessPolicy) {
	*out = *in
	if in.Inbound != nil {
		in, out := &in.Inbound, &out.Inbound
		*out = new(AccessPolicyInbound)
		(*in).DeepCopyInto(*out)
	}
	if in.Outbound != nil {
		in, out := &in.Outbound, &out.Outbound
		*out = new(AccessPolicyOutbound)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicy.
func (in *AccessPolicy) DeepCopy() *AccessPolicy {
	if in == nil {
		return nil
	}
	out := new(AccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicyExternalRule) DeepCopyInto(out *AccessPolicyExternalRule) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]AccessPolicyPortRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyExternalRule.
func (in *AccessPolicyExternalRule) DeepCopy() *AccessPolicyExternalRule {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyExternalRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicyInbound) DeepCopyInto(out *AccessPolicyInbound) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make(AccessPolicyInboundRules, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyInbound.
func (in *AccessPolicyInbound) DeepCopy() *AccessPolicyInbound {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyInbound)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicyInboundRule) DeepCopyInto(out *AccessPolicyInboundRule) {
	*out = *in
	out.AccessPolicyRule = in.AccessPolicyRule
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = new(AccessPolicyPermissions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyInboundRule.
func (in *AccessPolicyInboundRule) DeepCopy() *AccessPolicyInboundRule {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyInboundRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AccessPolicyInboundRules) DeepCopyInto(out *AccessPolicyInboundRules) {
	{
		in := &in
		*out = make(AccessPolicyInboundRules, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyInboundRules.
func (in AccessPolicyInboundRules) DeepCopy() AccessPolicyInboundRules {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyInboundRules)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicyOutbound) DeepCopyInto(out *AccessPolicyOutbound) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make(AccessPolicyRules, len(*in))
		copy(*out, *in)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = make([]AccessPolicyExternalRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyOutbound.
func (in *AccessPolicyOutbound) DeepCopy() *AccessPolicyOutbound {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyOutbound)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicyPermissions) DeepCopyInto(out *AccessPolicyPermissions) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]AccessPolicyPermission, len(*in))
		copy(*out, *in)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]AccessPolicyPermission, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyPermissions.
func (in *AccessPolicyPermissions) DeepCopy() *AccessPolicyPermissions {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyPermissions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicyPortRule) DeepCopyInto(out *AccessPolicyPortRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyPortRule.
func (in *AccessPolicyPortRule) DeepCopy() *AccessPolicyPortRule {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyPortRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicyRule) DeepCopyInto(out *AccessPolicyRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyRule.
func (in *AccessPolicyRule) DeepCopy() *AccessPolicyRule {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AccessPolicyRules) DeepCopyInto(out *AccessPolicyRules) {
	{
		in := &in
		*out = make(AccessPolicyRules, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyRules.
func (in AccessPolicyRules) DeepCopy() AccessPolicyRules {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyRules)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoInstrumentation) DeepCopyInto(out *AutoInstrumentation) {
	*out = *in
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]AutoInstrumentationDestination, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoInstrumentation.
func (in *AutoInstrumentation) DeepCopy() *AutoInstrumentation {
	if in == nil {
		return nil
	}
	out := new(AutoInstrumentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoInstrumentationDestination) DeepCopyInto(out *AutoInstrumentationDestination) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoInstrumentationDestination.
func (in *AutoInstrumentationDestination) DeepCopy() *AutoInstrumentationDestination {
	if in == nil {
		return nil
	}
	out := new(AutoInstrumentationDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Azure) DeepCopyInto(out *Azure) {
	*out = *in
	if in.Application != nil {
		in, out := &in.Application, &out.Application
		*out = new(AzureApplication)
		(*in).DeepCopyInto(*out)
	}
	if in.Sidecar != nil {
		in, out := &in.Sidecar, &out.Sidecar
		*out = new(AzureSidecar)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Azure.
func (in *Azure) DeepCopy() *Azure {
	if in == nil {
		return nil
	}
	out := new(Azure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAdApplication) DeepCopyInto(out *AzureAdApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAdApplication.
func (in *AzureAdApplication) DeepCopy() *AzureAdApplication {
	if in == nil {
		return nil
	}
	out := new(AzureAdApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureAdApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAdApplicationList) DeepCopyInto(out *AzureAdApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureAdApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAdApplicationList.
func (in *AzureAdApplicationList) DeepCopy() *AzureAdApplicationList {
	if in == nil {
		return nil
	}
	out := new(AzureAdApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureAdApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAdApplicationSpec) DeepCopyInto(out *AzureAdApplicationSpec) {
	*out = *in
	if in.AllowAllUsers != nil {
		in, out := &in.AllowAllUsers, &out.AllowAllUsers
		*out = new(bool)
		**out = **in
	}
	if in.Claims != nil {
		in, out := &in.Claims, &out.Claims
		*out = new(AzureAdClaims)
		(*in).DeepCopyInto(*out)
	}
	if in.PreAuthorizedApplications != nil {
		in, out := &in.PreAuthorizedApplications, &out.PreAuthorizedApplications
		*out = make([]AccessPolicyInboundRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReplyUrls != nil {
		in, out := &in.ReplyUrls, &out.ReplyUrls
		*out = make([]AzureAdReplyUrl, len(*in))
		copy(*out, *in)
	}
	if in.SinglePageApplication != nil {
		in, out := &in.SinglePageApplication, &out.SinglePageApplication
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAdApplicationSpec.
func (in *AzureAdApplicationSpec) DeepCopy() *AzureAdApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(AzureAdApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAdApplicationStatus) DeepCopyInto(out *AzureAdApplicationStatus) {
	*out = *in
	if in.CertificateKeyIds != nil {
		in, out := &in.CertificateKeyIds, &out.CertificateKeyIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PasswordKeyIds != nil {
		in, out := &in.PasswordKeyIds, &out.PasswordKeyIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SynchronizationSecretRotationTime != nil {
		in, out := &in.SynchronizationSecretRotationTime, &out.SynchronizationSecretRotationTime
		*out = (*in).DeepCopy()
	}
	if in.SynchronizationTime != nil {
		in, out := &in.SynchronizationTime, &out.SynchronizationTime
		*out = (*in).DeepCopy()
	}
	if in.PreAuthorizedApps != nil {
		in, out := &in.PreAuthorizedApps, &out.PreAuthorizedApps
		*out = new(AzureAdPreAuthorizedAppsStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAdApplicationStatus.
func (in *AzureAdApplicationStatus) DeepCopy() *AzureAdApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(AzureAdApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAdClaims) DeepCopyInto(out *AzureAdClaims) {
	*out = *in
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = make([]AzureAdExtraClaim, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]AzureAdGroup, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAdClaims.
func (in *AzureAdClaims) DeepCopy() *AzureAdClaims {
	if in == nil {
		return nil
	}
	out := new(AzureAdClaims)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAdGroup) DeepCopyInto(out *AzureAdGroup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAdGroup.
func (in *AzureAdGroup) DeepCopy() *AzureAdGroup {
	if in == nil {
		return nil
	}
	out := new(AzureAdGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAdPreAuthorizedApp) DeepCopyInto(out *AzureAdPreAuthorizedApp) {
	*out = *in
	if in.AccessPolicyRule != nil {
		in, out := &in.AccessPolicyRule, &out.AccessPolicyRule
		*out = new(AccessPolicyRule)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAdPreAuthorizedApp.
func (in *AzureAdPreAuthorizedApp) DeepCopy() *AzureAdPreAuthorizedApp {
	if in == nil {
		return nil
	}
	out := new(AzureAdPreAuthorizedApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAdPreAuthorizedAppsStatus) DeepCopyInto(out *AzureAdPreAuthorizedAppsStatus) {
	*out = *in
	if in.Assigned != nil {
		in, out := &in.Assigned, &out.Assigned
		*out = make([]AzureAdPreAuthorizedApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AssignedCount != nil {
		in, out := &in.AssignedCount, &out.AssignedCount
		*out = new(int)
		**out = **in
	}
	if in.Unassigned != nil {
		in, out := &in.Unassigned, &out.Unassigned
		*out = make([]AzureAdPreAuthorizedApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnassignedCount != nil {
		in, out := &in.UnassignedCount, &out.UnassignedCount
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAdPreAuthorizedAppsStatus.
func (in *AzureAdPreAuthorizedAppsStatus) DeepCopy() *AzureAdPreAuthorizedAppsStatus {
	if in == nil {
		return nil
	}
	out := new(AzureAdPreAuthorizedAppsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAdReplyUrl) DeepCopyInto(out *AzureAdReplyUrl) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAdReplyUrl.
func (in *AzureAdReplyUrl) DeepCopy() *AzureAdReplyUrl {
	if in == nil {
		return nil
	}
	out := new(AzureAdReplyUrl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureApplication) DeepCopyInto(out *AzureApplication) {
	*out = *in
	if in.ReplyURLs != nil {
		in, out := &in.ReplyURLs, &out.ReplyURLs
		*out = make([]AzureAdReplyUrlString, len(*in))
		copy(*out, *in)
	}
	if in.Claims != nil {
		in, out := &in.Claims, &out.Claims
		*out = new(AzureAdClaims)
		(*in).DeepCopyInto(*out)
	}
	if in.SinglePageApplication != nil {
		in, out := &in.SinglePageApplication, &out.SinglePageApplication
		*out = new(bool)
		**out = **in
	}
	if in.AllowAllUsers != nil {
		in, out := &in.AllowAllUsers, &out.AllowAllUsers
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureApplication.
func (in *AzureApplication) DeepCopy() *AzureApplication {
	if in == nil {
		return nil
	}
	out := new(AzureApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureNaisJob) DeepCopyInto(out *AzureNaisJob) {
	*out = *in
	if in.Application != nil {
		in, out := &in.Application, &out.Application
		*out = new(AzureApplication)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureNaisJob.
func (in *AzureNaisJob) DeepCopy() *AzureNaisJob {
	if in == nil {
		return nil
	}
	out := new(AzureNaisJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureSidecar) DeepCopyInto(out *AzureSidecar) {
	*out = *in
	in.Wonderwall.DeepCopyInto(&out.Wonderwall)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureSidecar.
func (in *AzureSidecar) DeepCopy() *AzureSidecar {
	if in == nil {
		return nil
	}
	out := new(AzureSidecar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudBigQueryDataset) DeepCopyInto(out *CloudBigQueryDataset) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudBigQueryDataset.
func (in *CloudBigQueryDataset) DeepCopy() *CloudBigQueryDataset {
	if in == nil {
		return nil
	}
	out := new(CloudBigQueryDataset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudIAMPermission) DeepCopyInto(out *CloudIAMPermission) {
	*out = *in
	out.Resource = in.Resource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudIAMPermission.
func (in *CloudIAMPermission) DeepCopy() *CloudIAMPermission {
	if in == nil {
		return nil
	}
	out := new(CloudIAMPermission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudIAMResource) DeepCopyInto(out *CloudIAMResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudIAMResource.
func (in *CloudIAMResource) DeepCopy() *CloudIAMResource {
	if in == nil {
		return nil
	}
	out := new(CloudIAMResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudSqlDatabase) DeepCopyInto(out *CloudSqlDatabase) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]CloudSqlDatabaseUser, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudSqlDatabase.
func (in *CloudSqlDatabase) DeepCopy() *CloudSqlDatabase {
	if in == nil {
		return nil
	}
	out := new(CloudSqlDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudSqlDatabaseUser) DeepCopyInto(out *CloudSqlDatabaseUser) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudSqlDatabaseUser.
func (in *CloudSqlDatabaseUser) DeepCopy() *CloudSqlDatabaseUser {
	if in == nil {
		return nil
	}
	out := new(CloudSqlDatabaseUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudSqlFlag) DeepCopyInto(out *CloudSqlFlag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudSqlFlag.
func (in *CloudSqlFlag) DeepCopy() *CloudSqlFlag {
	if in == nil {
		return nil
	}
	out := new(CloudSqlFlag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudSqlInstance) DeepCopyInto(out *CloudSqlInstance) {
	*out = *in
	if in.AutoBackupHour != nil {
		in, out := &in.AutoBackupHour, &out.AutoBackupHour
		*out = new(int)
		**out = **in
	}
	if in.RetainedBackups != nil {
		in, out := &in.RetainedBackups, &out.RetainedBackups
		*out = new(int)
		**out = **in
	}
	if in.TransactionLogRetentionDays != nil {
		in, out := &in.TransactionLogRetentionDays, &out.TransactionLogRetentionDays
		*out = new(int)
		**out = **in
	}
	if in.Maintenance != nil {
		in, out := &in.Maintenance, &out.Maintenance
		*out = new(Maintenance)
		(*in).DeepCopyInto(*out)
	}
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]CloudSqlDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Insights != nil {
		in, out := &in.Insights, &out.Insights
		*out = new(InsightsConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = make([]CloudSqlFlag, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudSqlInstance.
func (in *CloudSqlInstance) DeepCopy() *CloudSqlInstance {
	if in == nil {
		return nil
	}
	out := new(CloudSqlInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudStorageBucket) DeepCopyInto(out *CloudStorageBucket) {
	*out = *in
	if in.RetentionPeriodDays != nil {
		in, out := &in.RetentionPeriodDays, &out.RetentionPeriodDays
		*out = new(int)
		**out = **in
	}
	if in.LifecycleCondition != nil {
		in, out := &in.LifecycleCondition, &out.LifecycleCondition
		*out = new(LifecycleCondition)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudStorageBucket.
func (in *CloudStorageBucket) DeepCopy() *CloudStorageBucket {
	if in == nil {
		return nil
	}
	out := new(CloudStorageBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumedScope) DeepCopyInto(out *ConsumedScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumedScope.
func (in *ConsumedScope) DeepCopy() *ConsumedScope {
	if in == nil {
		return nil
	}
	out := new(ConsumedScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CpuScaling) DeepCopyInto(out *CpuScaling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CpuScaling.
func (in *CpuScaling) DeepCopy() *CpuScaling {
	if in == nil {
		return nil
	}
	out := new(CpuScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DigdiratorStatus) DeepCopyInto(out *DigdiratorStatus) {
	*out = *in
	if in.SynchronizationTime != nil {
		in, out := &in.SynchronizationTime, &out.SynchronizationTime
		*out = (*in).DeepCopy()
	}
	if in.KeyIDs != nil {
		in, out := &in.KeyIDs, &out.KeyIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = new([]v1.Condition)
		if **in != nil {
			in, out := *in, *out
			*out = make([]v1.Condition, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DigdiratorStatus.
func (in *DigdiratorStatus) DeepCopy() *DigdiratorStatus {
	if in == nil {
		return nil
	}
	out := new(DigdiratorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmptyDir) DeepCopyInto(out *EmptyDir) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmptyDir.
func (in *EmptyDir) DeepCopy() *EmptyDir {
	if in == nil {
		return nil
	}
	out := new(EmptyDir)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvFrom) DeepCopyInto(out *EnvFrom) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvFrom.
func (in *EnvFrom) DeepCopy() *EnvFrom {
	if in == nil {
		return nil
	}
	out := new(EnvFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVar) DeepCopyInto(out *EnvVar) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(EnvVarSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVar.
func (in *EnvVar) DeepCopy() *EnvVar {
	if in == nil {
		return nil
	}
	out := new(EnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVarSource) DeepCopyInto(out *EnvVarSource) {
	*out = *in
	out.FieldRef = in.FieldRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVarSource.
func (in *EnvVarSource) DeepCopy() *EnvVarSource {
	if in == nil {
		return nil
	}
	out := new(EnvVarSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in EnvVars) DeepCopyInto(out *EnvVars) {
	{
		in := &in
		*out = make(EnvVars, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVars.
func (in EnvVars) DeepCopy() EnvVars {
	if in == nil {
		return nil
	}
	out := new(EnvVars)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecAction) DeepCopyInto(out *ExecAction) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecAction.
func (in *ExecAction) DeepCopy() *ExecAction {
	if in == nil {
		return nil
	}
	out := new(ExecAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposedScope) DeepCopyInto(out *ExposedScope) {
	*out = *in
	if in.AtMaxAge != nil {
		in, out := &in.AtMaxAge, &out.AtMaxAge
		*out = new(int)
		**out = **in
	}
	if in.AllowedIntegrations != nil {
		in, out := &in.AllowedIntegrations, &out.AllowedIntegrations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Consumers != nil {
		in, out := &in.Consumers, &out.Consumers
		*out = make([]ExposedScopeConsumer, len(*in))
		copy(*out, *in)
	}
	if in.AccessibleForAll != nil {
		in, out := &in.AccessibleForAll, &out.AccessibleForAll
		*out = new(bool)
		**out = **in
	}
	if in.DelegationSource != nil {
		in, out := &in.DelegationSource, &out.DelegationSource
		*out = new(string)
		**out = **in
	}
	if in.Separator != nil {
		in, out := &in.Separator, &out.Separator
		*out = new(string)
		**out = **in
	}
	if in.Visibility != nil {
		in, out := &in.Visibility, &out.Visibility
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposedScope.
func (in *ExposedScope) DeepCopy() *ExposedScope {
	if in == nil {
		return nil
	}
	out := new(ExposedScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposedScopeConsumer) DeepCopyInto(out *ExposedScopeConsumer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposedScopeConsumer.
func (in *ExposedScopeConsumer) DeepCopy() *ExposedScopeConsumer {
	if in == nil {
		return nil
	}
	out := new(ExposedScopeConsumer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesFrom) DeepCopyInto(out *FilesFrom) {
	*out = *in
	if in.EmptyDir != nil {
		in, out := &in.EmptyDir, &out.EmptyDir
		*out = new(EmptyDir)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesFrom.
func (in *FilesFrom) DeepCopy() *FilesFrom {
	if in == nil {
		return nil
	}
	out := new(FilesFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Frontend) DeepCopyInto(out *Frontend) {
	*out = *in
	if in.GeneratedConfig != nil {
		in, out := &in.GeneratedConfig, &out.GeneratedConfig
		*out = new(FrontendGeneratedConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Frontend.
func (in *Frontend) DeepCopy() *Frontend {
	if in == nil {
		return nil
	}
	out := new(Frontend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendGeneratedConfig) DeepCopyInto(out *FrontendGeneratedConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendGeneratedConfig.
func (in *FrontendGeneratedConfig) DeepCopy() *FrontendGeneratedConfig {
	if in == nil {
		return nil
	}
	out := new(FrontendGeneratedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCP) DeepCopyInto(out *GCP) {
	*out = *in
	if in.BigQueryDatasets != nil {
		in, out := &in.BigQueryDatasets, &out.BigQueryDatasets
		*out = make([]CloudBigQueryDataset, len(*in))
		copy(*out, *in)
	}
	if in.Buckets != nil {
		in, out := &in.Buckets, &out.Buckets
		*out = make([]CloudStorageBucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SqlInstances != nil {
		in, out := &in.SqlInstances, &out.SqlInstances
		*out = make([]CloudSqlInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]CloudIAMPermission, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCP.
func (in *GCP) DeepCopy() *GCP {
	if in == nil {
		return nil
	}
	out := new(GCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpGetAction) DeepCopyInto(out *HttpGetAction) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpGetAction.
func (in *HttpGetAction) DeepCopy() *HttpGetAction {
	if in == nil {
		return nil
	}
	out := new(HttpGetAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IDPorten) DeepCopyInto(out *IDPorten) {
	*out = *in
	if in.Sidecar != nil {
		in, out := &in.Sidecar, &out.Sidecar
		*out = new(IDPortenSidecar)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IDPorten.
func (in *IDPorten) DeepCopy() *IDPorten {
	if in == nil {
		return nil
	}
	out := new(IDPorten)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IDPortenClient) DeepCopyInto(out *IDPortenClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IDPortenClient.
func (in *IDPortenClient) DeepCopy() *IDPortenClient {
	if in == nil {
		return nil
	}
	out := new(IDPortenClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IDPortenClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IDPortenClientList) DeepCopyInto(out *IDPortenClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IDPortenClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IDPortenClientList.
func (in *IDPortenClientList) DeepCopy() *IDPortenClientList {
	if in == nil {
		return nil
	}
	out := new(IDPortenClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IDPortenClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IDPortenClientSpec) DeepCopyInto(out *IDPortenClientSpec) {
	*out = *in
	if in.AccessTokenLifetime != nil {
		in, out := &in.AccessTokenLifetime, &out.AccessTokenLifetime
		*out = new(int)
		**out = **in
	}
	if in.PostLogoutRedirectURIs != nil {
		in, out := &in.PostLogoutRedirectURIs, &out.PostLogoutRedirectURIs
		*out = make([]IDPortenURI, len(*in))
		copy(*out, *in)
	}
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]IDPortenURI, len(*in))
		copy(*out, *in)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SessionLifetime != nil {
		in, out := &in.SessionLifetime, &out.SessionLifetime
		*out = new(int)
		**out = **in
	}
	if in.SSODisabled != nil {
		in, out := &in.SSODisabled, &out.SSODisabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IDPortenClientSpec.
func (in *IDPortenClientSpec) DeepCopy() *IDPortenClientSpec {
	if in == nil {
		return nil
	}
	out := new(IDPortenClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IDPortenSidecar) DeepCopyInto(out *IDPortenSidecar) {
	*out = *in
	in.Wonderwall.DeepCopyInto(&out.Wonderwall)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IDPortenSidecar.
func (in *IDPortenSidecar) DeepCopy() *IDPortenSidecar {
	if in == nil {
		return nil
	}
	out := new(IDPortenSidecar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Influx) DeepCopyInto(out *Influx) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Influx.
func (in *Influx) DeepCopy() *Influx {
	if in == nil {
		return nil
	}
	out := new(Influx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightsConfiguration) DeepCopyInto(out *InsightsConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightsConfiguration.
func (in *InsightsConfiguration) DeepCopy() *InsightsConfiguration {
	if in == nil {
		return nil
	}
	out := new(InsightsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Jwker) DeepCopyInto(out *Jwker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Jwker.
func (in *Jwker) DeepCopy() *Jwker {
	if in == nil {
		return nil
	}
	out := new(Jwker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Jwker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwkerList) DeepCopyInto(out *JwkerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Jwker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwkerList.
func (in *JwkerList) DeepCopy() *JwkerList {
	if in == nil {
		return nil
	}
	out := new(JwkerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JwkerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwkerSpec) DeepCopyInto(out *JwkerSpec) {
	*out = *in
	if in.AccessPolicy != nil {
		in, out := &in.AccessPolicy, &out.AccessPolicy
		*out = new(AccessPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwkerSpec.
func (in *JwkerSpec) DeepCopy() *JwkerSpec {
	if in == nil {
		return nil
	}
	out := new(JwkerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwkerStatus) DeepCopyInto(out *JwkerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwkerStatus.
func (in *JwkerStatus) DeepCopy() *JwkerStatus {
	if in == nil {
		return nil
	}
	out := new(JwkerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kafka) DeepCopyInto(out *Kafka) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kafka.
func (in *Kafka) DeepCopy() *Kafka {
	if in == nil {
		return nil
	}
	out := new(Kafka)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaScaling) DeepCopyInto(out *KafkaScaling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaScaling.
func (in *KafkaScaling) DeepCopy() *KafkaScaling {
	if in == nil {
		return nil
	}
	out := new(KafkaScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleCondition) DeepCopyInto(out *LifecycleCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleCondition.
func (in *LifecycleCondition) DeepCopy() *LifecycleCondition {
	if in == nil {
		return nil
	}
	out := new(LifecycleCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogDestination) DeepCopyInto(out *LogDestination) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogDestination.
func (in *LogDestination) DeepCopy() *LogDestination {
	if in == nil {
		return nil
	}
	out := new(LogDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Logging) DeepCopyInto(out *Logging) {
	*out = *in
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]LogDestination, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logging.
func (in *Logging) DeepCopy() *Logging {
	if in == nil {
		return nil
	}
	out := new(Logging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Login) DeepCopyInto(out *Login) {
	*out = *in
	if in.Enforce != nil {
		in, out := &in.Enforce, &out.Enforce
		*out = new(LoginEnforce)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Login.
func (in *Login) DeepCopy() *Login {
	if in == nil {
		return nil
	}
	out := new(Login)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginEnforce) DeepCopyInto(out *LoginEnforce) {
	*out = *in
	if in.ExcludePaths != nil {
		in, out := &in.ExcludePaths, &out.ExcludePaths
		*out = make([]WonderwallIgnorePaths, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginEnforce.
func (in *LoginEnforce) DeepCopy() *LoginEnforce {
	if in == nil {
		return nil
	}
	out := new(LoginEnforce)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Maintenance) DeepCopyInto(out *Maintenance) {
	*out = *in
	if in.Hour != nil {
		in, out := &in.Hour, &out.Hour
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Maintenance.
func (in *Maintenance) DeepCopy() *Maintenance {
	if in == nil {
		return nil
	}
	out := new(Maintenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Maskinporten) DeepCopyInto(out *Maskinporten) {
	*out = *in
	in.Scopes.DeepCopyInto(&out.Scopes)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Maskinporten.
func (in *Maskinporten) DeepCopy() *Maskinporten {
	if in == nil {
		return nil
	}
	out := new(Maskinporten)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaskinportenClient) DeepCopyInto(out *MaskinportenClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaskinportenClient.
func (in *MaskinportenClient) DeepCopy() *MaskinportenClient {
	if in == nil {
		return nil
	}
	out := new(MaskinportenClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaskinportenClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaskinportenClientList) DeepCopyInto(out *MaskinportenClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaskinportenClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaskinportenClientList.
func (in *MaskinportenClientList) DeepCopy() *MaskinportenClientList {
	if in == nil {
		return nil
	}
	out := new(MaskinportenClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaskinportenClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaskinportenClientSpec) DeepCopyInto(out *MaskinportenClientSpec) {
	*out = *in
	in.Scopes.DeepCopyInto(&out.Scopes)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaskinportenClientSpec.
func (in *MaskinportenClientSpec) DeepCopy() *MaskinportenClientSpec {
	if in == nil {
		return nil
	}
	out := new(MaskinportenClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaskinportenScope) DeepCopyInto(out *MaskinportenScope) {
	*out = *in
	if in.ConsumedScopes != nil {
		in, out := &in.ConsumedScopes, &out.ConsumedScopes
		*out = make([]ConsumedScope, len(*in))
		copy(*out, *in)
	}
	if in.ExposedScopes != nil {
		in, out := &in.ExposedScopes, &out.ExposedScopes
		*out = make([]ExposedScope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaskinportenScope.
func (in *MaskinportenScope) DeepCopy() *MaskinportenScope {
	if in == nil {
		return nil
	}
	out := new(MaskinportenScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Naisjob) DeepCopyInto(out *Naisjob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Naisjob.
func (in *Naisjob) DeepCopy() *Naisjob {
	if in == nil {
		return nil
	}
	out := new(Naisjob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Naisjob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NaisjobList) DeepCopyInto(out *NaisjobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Naisjob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NaisjobList.
func (in *NaisjobList) DeepCopy() *NaisjobList {
	if in == nil {
		return nil
	}
	out := new(NaisjobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NaisjobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NaisjobSpec) DeepCopyInto(out *NaisjobSpec) {
	*out = *in
	if in.AccessPolicy != nil {
		in, out := &in.AccessPolicy, &out.AccessPolicy
		*out = new(AccessPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureNaisJob)
		(*in).DeepCopyInto(*out)
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Completions != nil {
		in, out := &in.Completions, &out.Completions
		*out = new(int32)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(EnvVars, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]EnvFrom, len(*in))
		copy(*out, *in)
	}
	if in.FilesFrom != nil {
		in, out := &in.FilesFrom, &out.FilesFrom
		*out = make([]FilesFrom, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GCP)
		(*in).DeepCopyInto(*out)
	}
	if in.Influx != nil {
		in, out := &in.Influx, &out.Influx
		*out = new(Influx)
		**out = **in
	}
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(Kafka)
		**out = **in
	}
	if in.Liveness != nil {
		in, out := &in.Liveness, &out.Liveness
		*out = new(Probe)
		**out = **in
	}
	if in.Maskinporten != nil {
		in, out := &in.Maskinporten, &out.Maskinporten
		*out = new(Maskinporten)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenSearch != nil {
		in, out := &in.OpenSearch, &out.OpenSearch
		*out = new(OpenSearch)
		**out = **in
	}
	if in.Parallelism != nil {
		in, out := &in.Parallelism, &out.Parallelism
		*out = new(int32)
		**out = **in
	}
	if in.PreStopHook != nil {
		in, out := &in.PreStopHook, &out.PreStopHook
		*out = new(PreStopHook)
		(*in).DeepCopyInto(*out)
	}
	if in.Readiness != nil {
		in, out := &in.Readiness, &out.Readiness
		*out = new(Probe)
		**out = **in
	}
	if in.Redis != nil {
		in, out := &in.Redis, &out.Redis
		*out = make([]Redis, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.SecureLogs != nil {
		in, out := &in.SecureLogs, &out.SecureLogs
		*out = new(SecureLogs)
		**out = **in
	}
	if in.Startup != nil {
		in, out := &in.Startup, &out.Startup
		*out = new(Probe)
		**out = **in
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(Observability)
		(*in).DeepCopyInto(*out)
	}
	if in.Vault != nil {
		in, out := &in.Vault, &out.Vault
		*out = new(Vault)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NaisjobSpec.
func (in *NaisjobSpec) DeepCopy() *NaisjobSpec {
	if in == nil {
		return nil
	}
	out := new(NaisjobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectFieldSelector) DeepCopyInto(out *ObjectFieldSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectFieldSelector.
func (in *ObjectFieldSelector) DeepCopy() *ObjectFieldSelector {
	if in == nil {
		return nil
	}
	out := new(ObjectFieldSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Observability) DeepCopyInto(out *Observability) {
	*out = *in
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = new(Tracing)
		**out = **in
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(Logging)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoInstrumentation != nil {
		in, out := &in.AutoInstrumentation, &out.AutoInstrumentation
		*out = new(AutoInstrumentation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Observability.
func (in *Observability) DeepCopy() *Observability {
	if in == nil {
		return nil
	}
	out := new(Observability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearch) DeepCopyInto(out *OpenSearch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearch.
func (in *OpenSearch) DeepCopy() *OpenSearch {
	if in == nil {
		return nil
	}
	out := new(OpenSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreStopHook) DeepCopyInto(out *PreStopHook) {
	*out = *in
	if in.Exec != nil {
		in, out := &in.Exec, &out.Exec
		*out = new(ExecAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Http != nil {
		in, out := &in.Http, &out.Http
		*out = new(HttpGetAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreStopHook.
func (in *PreStopHook) DeepCopy() *PreStopHook {
	if in == nil {
		return nil
	}
	out := new(PreStopHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Probe) DeepCopyInto(out *Probe) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Probe.
func (in *Probe) DeepCopy() *Probe {
	if in == nil {
		return nil
	}
	out := new(Probe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConfig) DeepCopyInto(out *PrometheusConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConfig.
func (in *PrometheusConfig) DeepCopy() *PrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Redirect) DeepCopyInto(out *Redirect) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Redirect.
func (in *Redirect) DeepCopy() *Redirect {
	if in == nil {
		return nil
	}
	out := new(Redirect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Redis) DeepCopyInto(out *Redis) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Redis.
func (in *Redis) DeepCopy() *Redis {
	if in == nil {
		return nil
	}
	out := new(Redis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Replicas) DeepCopyInto(out *Replicas) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int)
		**out = **in
	}
	if in.ScalingStrategy != nil {
		in, out := &in.ScalingStrategy, &out.ScalingStrategy
		*out = new(ScalingStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Replicas.
func (in *Replicas) DeepCopy() *Replicas {
	if in == nil {
		return nil
	}
	out := new(Replicas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(ResourceSpec)
		**out = **in
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(ResourceSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSpec.
func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingStrategy) DeepCopyInto(out *ScalingStrategy) {
	*out = *in
	if in.Cpu != nil {
		in, out := &in.Cpu, &out.Cpu
		*out = new(CpuScaling)
		**out = **in
	}
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(KafkaScaling)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingStrategy.
func (in *ScalingStrategy) DeepCopy() *ScalingStrategy {
	if in == nil {
		return nil
	}
	out := new(ScalingStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretPath) DeepCopyInto(out *SecretPath) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretPath.
func (in *SecretPath) DeepCopy() *SecretPath {
	if in == nil {
		return nil
	}
	out := new(SecretPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureLogs) DeepCopyInto(out *SecureLogs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureLogs.
func (in *SecureLogs) DeepCopy() *SecureLogs {
	if in == nil {
		return nil
	}
	out := new(SecureLogs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = new([]v1.Condition)
		if **in != nil {
			in, out := *in, *out
			*out = make([]v1.Condition, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Strategy) DeepCopyInto(out *Strategy) {
	*out = *in
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(appsv1.RollingUpdateDeployment)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Strategy.
func (in *Strategy) DeepCopy() *Strategy {
	if in == nil {
		return nil
	}
	out := new(Strategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenX) DeepCopyInto(out *TokenX) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenX.
func (in *TokenX) DeepCopy() *TokenX {
	if in == nil {
		return nil
	}
	out := new(TokenX)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tracing) DeepCopyInto(out *Tracing) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tracing.
func (in *Tracing) DeepCopy() *Tracing {
	if in == nil {
		return nil
	}
	out := new(Tracing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vault) DeepCopyInto(out *Vault) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]SecretPath, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vault.
func (in *Vault) DeepCopy() *Vault {
	if in == nil {
		return nil
	}
	out := new(Vault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wonderwall) DeepCopyInto(out *Wonderwall) {
	*out = *in
	if in.AutoLoginIgnorePaths != nil {
		in, out := &in.AutoLoginIgnorePaths, &out.AutoLoginIgnorePaths
		*out = make([]WonderwallIgnorePaths, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wonderwall.
func (in *Wonderwall) DeepCopy() *Wonderwall {
	if in == nil {
		return nil
	}
	out := new(Wonderwall)
	in.DeepCopyInto(out)
	return out
}
