//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package controller

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NaisStatus) DeepCopyInto(out *NaisStatus) {
	*out = *in
	if in.SynchronizationTime != nil {
		in, out := &in.SynchronizationTime, &out.SynchronizationTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NaisStatus.
func (in *NaisStatus) DeepCopy() *NaisStatus {
	if in == nil {
		return nil
	}
	out := new(NaisStatus)
	in.DeepCopyInto(out)
	return out
}
